### ISSUE TITLE
Actividad 2_Ejercicio de Conversiones

### ISSUE THREAD

**Issue by A-Lorely-Z** [SistemasTecTlaxiaco/actividad-2-ejercicios-lennin-s-team-1as#1]
[Actividad 2_Matematicas Discretas.pdf](https://github.com/user-attachments/files/16830602/Actividad.2_Matematicas.Discretas.pdf)

**Comment by AlynGomez12** [comment]
Portada 25/25
Procedimiento 25/25
Figuras 25/25
Resultados 25/25
Calificación final 100

**Comment by josealfredo79** [comment]
bien hecho y revisado
