### ISSUE TITLE
Practica 2.Operaciones con Conjuntos

### ISSUE THREAD

**Issue by A-Lorely-Z** [SistemasTecTlaxiaco/actividad-2-ejercicios-lennin-s-team-1as#2]
[Conjuntos.Practica_1[1].pdf](https://github.com/user-attachments/files/17123051/Conjuntos.Practica_1.1.pdf)

**Comment by Johnc-byte** [comment]
Portada 25/25
Procedimiento 25/25
Figuras, ilustraciones y fotografías. 25/25
Resultados y conclusiones 25/25
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
